learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # adicionando o user
    path('users/', include('users.urls')),
    # adicioando a URL específica 
    path('', include('learning_logs.urls')),
]

learning_log/learning_logs/urls.py
""" Define padrões de URL para learning_logs. """

from django.urls import path
from . import views

# nome do aplicativo
app_name = "learning_logs"

# padrões de URL
urlpatterns = [
    # página inicial 
    path('', views.index, name='index'),
    
    # mostra todos os assuntos
    path('topics/', views.topics, name='topics'),
    
    # página de detalhes para um único assunto
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # página para adicionar um novo assunto
    path('new_topic/', views.new_topic, name='new_topic'),

    # página para adicionar uma nova entrada url
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # Página para editar uma entrada url
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

learning_log/users/urls.py
""" Define padrões de URL para users. """

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # login quanto logout estão aqui 
    path('', include('django.contrib.auth.urls')),
    
    # página de cadastro
    path('register/', views.register, name='register'), 
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """ Um assunto sobre o qual o usuário está aprendendo. """
    
    # texto armazenado no banco de dados
    text = models.CharField(max_length=200)
    
    # registrará a data e hora 
    date_added = models.DateTimeField(auto_now_add=True)

    # torando o atributo público
    public = models.fields.BooleanField(default=False)

    # relação entre user e cahve estrangeira 
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """ Devolve uma representação em string do modelo. """

        return self.text
    

class Entry(models.Model):
    """ Algo específico aprendido sobre um assunto. """
    
    # referência a outro registro do banco de dados
    # associa cada entrada a um assunto em específico
    # cada assunto recebe uma chave, um ID. Sendo este dado a conexão entre os BD's
    # precisei adicionar on_delete pois trata-se de uma versão nova do Django 2.0 
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    # não se quer restringir a quantiade de caracter
    text = models.TextField()

    # torando o atributo público
    public = models.fields.BooleanField(default=False)

    # apresenta em ordem que foram criadas e inserem um timestamp junto a cada entrada
    date_added = models.DateTimeField(auto_now_add=True)

    # precisa estar dentro de Entry
    class Meta:
        """ Armazena as informações extras para adminstrar um modelo. """

        # quando fro se referir a mais de uma entrada utilizar entries ao invés de Entrys
        verbose_name_plural = 'entries'

    def __str__(self):
        """ Devolve uma representação em string do modelo. """
        
        return self.text[:50] + "..."

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry   

class TopicForm(forms.ModelForm):
    
    class Meta:
        """ Modelo de formulário que o usuário irá preencher. """

        # herdando as características de Topic
        model = Topic

        # selecionando apenas o texto de Topic
        fields = ['text']

        # espeficando um rótulo vazio de texto
        labels = {'text': ''}

class EntryForm(forms.ModelForm):

    class Meta:
    
        # herda as características de Entry
        model = Entry

        # selecioando apenas o texto de Entry
        fields = ['text']

        # espeficando um rótulo vazio de texto
        labels = {'text': ''}

        # criando uma caixa de texto de 80 colunas
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """ A página inicial de Learning Log. """

    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """ Mostra todos os tópicos. """

    # consulta-se o  banco de dados pedindo os objetos de Topic, ordenados com o atributo date_added
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')

    # contexto que será enviado ao template
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """ Mostra um único assunto e todas as suas entradas. """

    # topic armazena o assunto .get()
    topic = get_object_or_404(Topic, id=topic_id)

    # garante que o assunto pertence ao usuário atual
    if not topic.public:
        check_topic_owner(topic, request)

    # os assuntos são recuperados e organizados
    entries = topic.entry_set.order_by('-date_added')

    # os assuntos são armazenados dentro do dicionário para o html
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """ Adiciona um novo assunto. """

    if request.method != 'POST':

        # nenhum dado submetido; cria um formulário em branco
        form = TopicForm()
    else:
        
        # dados do POST submetidos; processa os dados
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            
            return redirect('learning_logs:topics')

    # exibir um formulário em branco ou inválido
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """ Acrescenta uma nova entrada para um assunto em particular. """
    
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        
        # nenhum dado submetido; cria um formulário em branco
        form = EntryForm()
    else:

        # dados do POST submetidos; processa os dados
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()

            return redirect('learning_logs:topic', topic_id=topic_id)

    # exibir um formulário em branco ou inválido 
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """ Edita uma entrada existente. """

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic, request)

    if request.method != 'POST':

        # requisição inicial; preenche previamente o formulário com a entrada atual
        form = EntryForm(instance=entry)
    else:
        
        # Dados de POST submetidos; processa os dados
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()

            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

def check_topic_owner(topic, request):
    """ Verifica se o tópico corresponde ao usuário atual. """
    
    if topic.owner != request.user:
        raise Http404

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """ Faz o cadastro de um novo usuário. """

    if request.method != 'POST':

        # exibe um formulário de cadastro em branco
        form = UserCreationForm()
    else:
        
        # processa o formulário preenchido
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()

            # faz login do usuário e o redicreciona para o página inicial
            login(request, new_user)
            return redirect('learning_logs:index')

    # exibe um formulário em branco ou inválido 
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
<p> 
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -

    <a href="{% url 'learning_logs:topics' %}">Topics</a> -

    {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
    <a href="{% url 'users:register'%}">register</a> -
    <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
    
</p>

{% block content %}{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}


{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="btn btn-primary">save changes</button>
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Add a new topic:</p>

  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add topic</button>
  </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>
    Topic: {{ topic }}
</p>
<p>
    Entries:  
</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>
            {{ entry.date_added|date:'M d, Y H:i' }}
        </p>

        <p>
            {{ entry.text|linebreaks }}
        </p>
        
        <p>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
        </p>
    </li>
    {% empty %}
    <li>
        There are no entries for this topic yet.
    </li>
    {% endfor %}
</ul>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Topics</p>
<ul> 
    {% for topic in topics %}
    <li>
        <a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a>
    </li> 
    {% empty %}
    <li>
        No topics have been added yet. 
    </li>
    {% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}